apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  securityContext:
      runAsUser: 0
  containers:
  - name: app
    image: apache/zeppelin:latest
    command: ["/bin/sh", "-c"]
    args: ["tail -f /dev/null"]
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["SYS_RAWIO","SYS_RESOURCE","SYS_NICE","IPC_OWNER","SYS_ADMIN","CAP_MKNOD"]
    volumeMounts:
    - mountPath: /host/dev
      name: hostpath-volume
    - mountPath: /sys/fs/cgroup
      name: sys-host
    volumeDevices:
    - name: data
      devicePath: /dev/local
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /dev
  - name: sys-host
    hostPath:
      path: /sys/fs/cgroup
  - name: data
    persistentVolumeClaim:
      claimName: horcrux-lv1